{% set name = "permamodel" %}
{% set version = "0.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/permamodel/permamodel
  git_rev: v{{ version }}

requirements:
  build:
    - python
  run:
    - numpy
    - scipy
    - netcdf4
    - affine
    - python-dateutil
    - pyyaml

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

test:
  requires:
    - nose
    - bmi-tester
  imports:
    - permamodel
    - permamodel.components
  commands:
    - curl https://raw.githubusercontent.com/permamodel/permamodel/master/permamodel/examples/Frostnumber_example_singlesite_singleyear.cfg -o example.cfg
    - bmi-tester permamodel.components.bmi_frost_number.BmiFrostnumberMethod --infile=example.cfg
    # - nosetests --with-doctest permamodel  ## Borked. See line 134 of frost_number.py

about:
  home: https://github.com/permamodel/permamodel
  license: MIT
  summary: a collection of numerical permafrost models
  dev_url: https://github.com/permamodel/permamodel
