{% set name = "permamodel" %}
{% set version = "0.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mcflugen/{{ name }}/archive/v{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: dd77d224e05973c5dbb1468692c3c7efeee2ed14d9a47c94a38f5e4e374ef29b

build:
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - setuptools
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - netcdf4
    - affine
    - python-dateutil
    - pyyaml

test:
  requires:
    - nose
  imports:
    - permamodel
    - permamodel.components
  # commands:
  #   - nosetests --with-doctest permamodel
  #   - curl https://raw.githubusercontent.com/permamodel/permamodel/master/permamodel/examples/Frostnumber_example_singlesite_singleyear.cfg -o example.cfg
  #   - bmi-tester permamodel.components.bmi_frost_number.BmiFrostnumberMethod --infile=example.cfg

about:
  home: https://github.com/permamodel/permamodel
  license: MIT
  summary: A collection of numerical permafrost models.
  dev_url: https://github.com/permamodel/permamodel
