{% set name = "permamodel" %}
{% set version = "0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/permamodel/permamodel

requirements:
  build:
    - python
    - numpy
    - nose
  run:
    - python
    - numpy
    - nose

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

test:
  requires:
    - bmi-tester
  imports:
    - permamodel
    - permamodel.components
  commands:
    - curl https://raw.githubusercontent.com/permamodel/permamodel/master/permamodel/examples/Frostnumber_example_singlesite_singleyear.cfg -o example.cfg
    - bmi-tester permamodel.components.bmi_frost_number.BmiFrostnumberMethod --input=example.cfg
    # - nosetests --with-doctest permamodel

about:
  home: https://github.com/permamodel/permamodel
  license: MIT
  summary: a collection of numerical permafrost models
  dev_url: https://github.com/permamodel/permamodel
